CC=gcc
CFLAGS=-Wall -Werror

q3: q3.o BST.o
q3.o: q3.c BST.h

q5: q5.o BST.o
q5.o: q5.c BST.h

q7: q7.o BST.o
q7.o: q7.c BST.h

q8: q8.o BST.o
q8.o: q8.c BST.h

q11: q11.o BST.o
q11.o: q11.c BST.h

BST.o: BST.c BST.h

clean:
	rm -f *.o length q3 q5 q7 q8 q11
