CC=gcc
CFLAGS=-Wall -Werror
LDLIBS=-lm

palindrome: palindrome.c
evalPolynomial: evalPolynomial.o
printPermutation: printPermutation.o
strToLower: strToLower.o

*.o: *.c

clean:
	rm -f *.o palindrome evalPolynomial printPermutation strToLower
