CC=gcc
CFLAGS=-Wall -Werror
LDLIBS=-lm

evalPolynomial: evalPolynomial.o
printPermutation: printPermutation.o
strToLower: strToLower.o

*.o: *.c

clean:
	rm -f *.o evalPolynomial printPermutation strToLower
